#!/bin/bash
# make-vectors.sh: regenerate the CRB1 (Crumb v1 visible record) shared
# conformance corpus. Language-neutral contract: ../CRUMB_READER_CONTRACT.md.
#
# Usage: make-vectors.sh CRUMBS_BIN OUT_DIR
#   CRUMBS_BIN  the `crumbs` tool from aien-sovereign-core (crates/crumbs),
#               built with: cargo build -p crumbs --bin crumbs
#   OUT_DIR     normally specs/crumb-visible/vectors
#
# Three groups of vectors, all listed in OUT_DIR/expected.txt:
#   vNNN.crb  positive, one per registered crumb family, written by
#             `crumbs vectors` (seed 7); expected lines copied from its output.
#   pNNN.crb  positive edge cases built byte by byte below (budget present,
#             max u64, raw lanes, 64 examples).
#   rNNN.crb  refusal cases built byte by byte below, each with the contract
#             refusal code the first failing check must produce.
# The expected outcome of every p and r vector is checked by the Rust
# reference (crates/crumbs/tests/visible_conformance.rs); nothing here is
# trusted on its own. Shell only: no Python, no outside tools beyond coreutils.
set -eu
export LC_ALL=C
CRUMBS=${1:?CRUMBS_BIN}
OUT=${2:?OUT_DIR}
mkdir -p "$OUT"
rm -f "$OUT"/v*.crb "$OUT"/p*.crb "$OUT"/r*.crb "$OUT"/expected.txt
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

"$CRUMBS" vectors "$tmp/gen" >/dev/null
cp "$tmp"/gen/v*.crb "$OUT"/

# ---- byte helpers -------------------------------------------------------
u8() { printf "\\x$(printf %02x "$1")"; }
le16() { u8 $(($1 & 255)); u8 $((($1 >> 8) & 255)); }
le32() { for s in 0 8 16 24; do u8 $((($1 >> s) & 255)); done; }
# hdr ENC FLAGS IN_ARITY OUT_ARITY IN_LB OUT_LB N  (schema 1)
hdr() { printf 'CRB1'; le16 1; u8 "$1"; u8 "$2"; u8 "$3"; u8 "$4"; u8 "$5"; u8 "$6"; le32 "$7"; }
# blob TEXT : u32 length + bytes of TEXT
blob() { le32 ${#1}; printf '%s' "$1"; }
# hexblob HEX... : u32 length + raw bytes
hexblob() { le32 $#; for h in "$@"; do printf "\\x$h"; done; }
# patch FILE OFFSET HEX... : copy of FILE with bytes replaced at OFFSET
patch() {
    local f=$1 off=$2
    shift 2
    head -c "$off" "$f"
    for h in "$@"; do printf "\\x$h"; done
    tail -c +$((off + 1 + $#)) "$f"
}

{
    echo "# CRB1 shared conformance corpus. Contract: CRUMB_READER_CONTRACT.md (contract 1.0.0, schema 1)."
    echo "# Line: <file> ok enc=E in=AxB out=AxB n=N[ budget=C,D,Q,P] | in... -> out... | ..."
    echo "#   or: <file> refuse <code>   (codes: -1 MAGIC -2 VERSION -3 SHAPE -4 LANE -5 LENGTH -6 NONCANONICAL)"
    echo "# Generated by tools/make-vectors.sh; do not edit by hand."
    cat "$tmp/gen/expected.txt"
} >"$OUT/expected.txt"
ok() { echo "$1 ok $2" >>"$OUT/expected.txt"; }
refuse() { echo "$1 refuse $2" >>"$OUT/expected.txt"; }

V1="$OUT/v001.crb" # decimal, 1x0 -> 1x0, n=8, no budget
v1line=$(grep '^v001.crb ' "$tmp/gen/expected.txt" | sed 's/^v001.crb ok //')

# ---- positive edge cases ------------------------------------------------
# p001: budget present (v001 with flags bit0 and four budget words).
{ patch "$V1" 7 01; le32 1; le32 2; le32 3; le32 4; } >"$OUT/p001.crb"
ok p001.crb "$(echo "$v1line" | sed 's/ n=8 / n=8 budget=1,2,3,4 /')"
# p002: decimal zero and max u64.
{ hdr 1 0 2 1 0 0 1; blob "0 18446744073709551615"; blob "7"; } >"$OUT/p002.crb"
ok p002.crb "enc=1 in=2x0 out=1x0 n=1 | 0 18446744073709551615 -> 7"
# p003: raw lanes, 8 one-byte lanes in, one 8-byte lane out (all ones).
{ hdr 2 0 8 1 1 8 1; hexblob 00 01 02 03 04 05 06 07; hexblob ff ff ff ff ff ff ff ff; } >"$OUT/p003.crb"
ok p003.crb "enc=2 in=8x1 out=1x8 n=1 | 0 1 2 3 4 5 6 7 -> 18446744073709551615"
# p004: 64 examples (the maximum), decimal i -> i+1.
line="enc=1 in=1x0 out=1x0 n=64"
{
    hdr 1 0 1 1 0 0 64
    for i in $(seq 0 63); do blob "$i"; blob "$((i + 1))"; done
} >"$OUT/p004.crb"
for i in $(seq 0 63); do line="$line | $i -> $((i + 1))"; done
ok p004.crb "$line"
# p005: raw two-byte lanes, little-endian order.
{ hdr 2 0 2 1 2 2 1; hexblob 34 12 00 80; hexblob ff ff; } >"$OUT/p005.crb"
ok p005.crb "enc=2 in=2x2 out=1x2 n=1 | 4660 32768 -> 65535"

# ---- refusal cases (first failing check in contract order wins) ---------
M() { hdr 1 0 1 1 0 0 1; blob 1; blob 2; } # minimal valid decimal crumb
M >"$tmp/m.crb"
: >"$OUT/r001.crb";                                      refuse r001.crb -5 # empty
printf 'CRB' >"$OUT/r002.crb";                           refuse r002.crb -5 # shorter than magic
patch "$V1" 0 58 >"$OUT/r003.crb";                       refuse r003.crb -1 # magic XRB1
patch "$V1" 0 63 72 62 31 >"$OUT/r004.crb";              refuse r004.crb -1 # magic crb1
patch "$V1" 4 02 00 >"$OUT/r005.crb";                    refuse r005.crb -2 # schema 2
patch "$V1" 4 00 00 >"$OUT/r006.crb";                    refuse r006.crb -2 # schema 0
head -c 5 "$V1" >"$OUT/r007.crb";                        refuse r007.crb -5 # cut inside schema
head -c 10 "$V1" >"$OUT/r008.crb";                       refuse r008.crb -5 # cut inside header
patch "$tmp/m.crb" 6 00 >"$OUT/r009.crb";                refuse r009.crb -3 # encoding 0
patch "$tmp/m.crb" 6 03 >"$OUT/r010.crb";                refuse r010.crb -3 # encoding 3
patch "$tmp/m.crb" 7 02 >"$OUT/r011.crb";                refuse r011.crb -6 # flags bit1
patch "$tmp/m.crb" 7 80 >"$OUT/r012.crb";                refuse r012.crb -6 # flags bit7
patch "$tmp/m.crb" 8 00 >"$OUT/r013.crb";                refuse r013.crb -3 # in_arity 0
patch "$tmp/m.crb" 9 09 >"$OUT/r014.crb";                refuse r014.crb -3 # out_arity 9
patch "$tmp/m.crb" 10 01 >"$OUT/r015.crb";               refuse r015.crb -3 # decimal with lane bytes 1
{ hdr 2 0 1 1 3 1 1; hexblob 00 00 00; hexblob 00; } >"$OUT/r016.crb"; refuse r016.crb -3 # raw lane bytes 3
{ hdr 2 0 1 1 1 0 1; hexblob 00; } >"$OUT/r017.crb";     refuse r017.crb -3 # raw lane bytes 0
{ hdr 1 0 1 1 0 0 0; } >"$OUT/r018.crb";                 refuse r018.crb -5 # n = 0
{ hdr 1 0 1 1 0 0 65; } >"$OUT/r019.crb";                refuse r019.crb -5 # n = 65
head -c 20 "$V1" >"$OUT/r020.crb";                       refuse r020.crb -5 # cut inside examples
{ cat "$V1"; u8 0; } >"$OUT/r021.crb";                   refuse r021.crb -5 # one trailing byte
{ hdr 1 0 1 1 0 0 1; blob "$(printf '1%.0s' $(seq 1 169))"; blob 2; } >"$OUT/r022.crb"; refuse r022.crb -5 # example field 169 bytes (> 168)
{ hdr 1 0 1 1 0 0 1; le32 9; printf '1'; } >"$OUT/r023.crb"; refuse r023.crb -5 # length past end
{ hdr 1 0 1 1 0 0 1; blob 03; blob 2; } >"$OUT/r024.crb"; refuse r024.crb -6 # leading zero
{ hdr 1 0 1 1 0 0 1; blob +5; blob 2; } >"$OUT/r025.crb"; refuse r025.crb -6 # sign
{ hdr 1 0 1 1 0 0 1; blob ""; blob 2; } >"$OUT/r026.crb"; refuse r026.crb -6 # empty lane
{ hdr 1 0 1 1 0 0 1; blob "1 2"; blob 2; } >"$OUT/r027.crb"; refuse r027.crb -4 # too many lanes
{ hdr 1 0 2 1 0 0 1; blob "1  2"; blob 2; } >"$OUT/r028.crb"; refuse r028.crb -4 # double space
{ hdr 1 0 1 1 0 0 1; blob "5 "; blob 2; } >"$OUT/r029.crb"; refuse r029.crb -4 # trailing space
{ hdr 1 0 1 1 0 0 1; blob 18446744073709551616; blob 2; } >"$OUT/r030.crb"; refuse r030.crb -4 # u64 overflow
{ hdr 1 0 1 1 0 0 1; hexblob ff; blob 2; } >"$OUT/r031.crb"; refuse r031.crb -4 # invalid UTF-8
{ hdr 1 0 1 1 0 0 1; hexblob c3 a9; blob 2; } >"$OUT/r032.crb"; refuse r032.crb -6 # valid UTF-8, not a digit
{ hdr 2 0 1 1 4 4 1; hexblob 00 00 00; hexblob 00 00 00 00; } >"$OUT/r033.crb"; refuse r033.crb -4 # raw lane length
patch "$tmp/m.crb" 7 01 >"$OUT/r034.crb";                refuse r034.crb -5 # budget flag, no budget
{ patch "$tmp/m.crb" 7 01; le32 1; le32 2; } >"$OUT/r035.crb"; refuse r035.crb -5 # budget cut short
{ M; le32 1; le32 2; le32 3; le32 4; } >"$OUT/r036.crb"; refuse r036.crb -5 # budget bytes, flag clear
{ hdr 1 0 1 1 0 0 1; blob 03; le32 2; } >"$OUT/r037.crb"; refuse r037.crb -5 # order: output read before input lanes
patch "$tmp/m.crb" 6 03 02 >"$OUT/r038.crb";             refuse r038.crb -3 # order: encoding before flags
patch "$tmp/m.crb" 7 02 00 >"$OUT/r039.crb";             refuse r039.crb -6 # order: flags before arity
{ printf 'CRB1'; le16 1; u8 1; u8 0; u8 0; } >"$OUT/r040.crb"; refuse r040.crb -5 # order: whole header read before arity check
{ hdr 1 0 1 1 0 0 1; blob 1; blob 03; } >"$OUT/r041.crb"; refuse r041.crb -6 # leading zero on output side
{ hdr 1 0 1 1 0 0 2; blob 1; blob 2; blob 01; blob 2; } >"$OUT/r042.crb"; refuse r042.crb -6 # second example bad
patch "$tmp/m.crb" 4 01 01 >"$OUT/r043.crb";             refuse r043.crb -2 # schema 257 (high byte)
{ hdr 1 0 1 1 0 0 1; blob 1; blob "2 3"; } >"$OUT/r044.crb"; refuse r044.crb -4 # output lane count

nv=$(ls "$OUT"/v*.crb | wc -l)
np=$(ls "$OUT"/p*.crb | wc -l)
nr=$(ls "$OUT"/r*.crb | wc -l)
echo "CRB1 vectors written: family=$nv edge=$np refusal=$nr"
